//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FBLA_Members.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FBLA_Members.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;HTML&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;
        ///		How do I add a member?
        ///	&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;BODY style=&quot;background-color: #2d89ef; font-family: Segoe UI Light; color:white&quot;&gt;
        ///	&lt;p&gt;On the main page, click &lt;strong&gt;Add&lt;/strong&gt;. A dialog box will pop up with all the various fields you can enter
        ///	for a user. Click OK to add the user, or Cancel to cancel.
        ///	&lt;/p&gt;
        ///&lt;/BODY&gt;
        ///&lt;/HTML&gt;.
        /// </summary>
        internal static string AddMember {
            get {
                return ResourceManager.GetString("AddMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;HTML&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;
        ///		How do I create a DB?
        ///	&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;BODY style=&quot;background-color: #2d89ef; font-family: Segoe UI Light; color:white;&quot;&gt;
        ///	&lt;p&gt;To create a new database, click the &lt;strong&gt;File&lt;/strong&gt; button on the menu strip of the application, and then click
        ///		&lt;strong&gt;New&lt;/strong&gt; button. You will see a dialog pop up on your screen. You can now enter the name of the database
        ///		file you wish to create. Click &apos;Save&apos; when you are finished.
        ///	&lt;/p&gt;
        ///&lt;/BODY&gt;
        ///&lt;/HTML&gt;.
        /// </summary>
        internal static string CreateDB {
            get {
                return ResourceManager.GetString("CreateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;HTML&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;
        ///		How do I create a custom report?
        ///	&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;BODY style=&quot;background-color: #2d89ef; font-family: Segoe UI Light; color:white;&quot;&gt;
        ///	&lt;p&gt;To create your own report, please click &lt;strong&gt;Reports&lt;/strong&gt; -&gt; &lt;strong&gt;Custom&lt;/strong&gt; -&gt; &lt;strong&gt;New Template&lt;/strong&gt;.
        ///		This will give you a text box in which you can use HTML, CSS, and JavaScript to create a custom report style. The
        ///		variables you can use are: @TITLE, @BODY, @ACTIVE_MEMBERS, @NONACTIVE_MEMBERS, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CustomReport {
            get {
                return ResourceManager.GetString("CustomReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;HTML&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;
        ///		How do I create a report?
        ///	&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;BODY style=&quot;background-color: #2d89ef; font-family: Segoe UI Light; color:white;&quot;&gt;
        ///	&lt;h1&gt;Quick Report #1&lt;/h1&gt;
        ///	&lt;p&gt;To view a list of all members by state, the number of active and non-active members, the number of
        ///		members that owe money, and the amount of money owed, click &lt;strong&gt;Reports&lt;/strong&gt; -&gt; &lt;strong&gt;Quick Report #1&lt;/strong&gt;.
        ///		This will generate an HTML file that you may save or print.
        ///	&lt;/p&gt;
        ///	
        ///	&lt;h1&gt;Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MakeReport {
            get {
                return ResourceManager.GetString("MakeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;HTML&gt;
        ///&lt;head&gt;
        ///	&lt;title&gt;
        ///		How do I open a DB?
        ///	&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;BODY style=&quot;background-color: #2d89ef; font-family: Segoe UI Light; color:white;&quot;&gt;
        ///	&lt;p&gt;To open an existing SQLite database, click &lt;strong&gt;File&lt;/strong&gt; -&gt; &lt;strong&gt;Open&lt;/strong. There
        ///		will be a dialog which will allow you to browse your file system and locate a database file.
        ///		Either double click or select &apos;Open&apos; to open the file.
        ///	&lt;/p&gt;
        ///&lt;/BODY&gt;
        ///&lt;/HTML&gt;.
        /// </summary>
        internal static string OpenDB {
            get {
                return ResourceManager.GetString("OpenDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;#TITLE&lt;/title&gt;
        ///    &lt;style&gt;
        ///        html {
        ///            font-family: sans-serif;
        ///            -ms-text-size-adjust: 100%;
        ///            -webkit-text-size-adjust: 100%
        ///        }
        ///        
        ///        body {
        ///            margin: 0
        ///        }
        ///        
        ///        article,
        ///        aside,
        ///        details,
        ///        figcaption,
        ///        figure,
        ///        footer,
        ///        header,
        ///        hgroup,
        ///        main,
        ///        menu,
        ///        nav,
        ///        section,
        ///        summar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReportBasic {
            get {
                return ResourceManager.GetString("ReportBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;title&gt;#TITLE&lt;/title&gt;
        ///    &lt;style&gt;
        ///        html {
        ///            font-family: sans-serif;
        ///            -ms-text-size-adjust: 100%;
        ///            -webkit-text-size-adjust: 100%
        ///        }
        ///        
        ///        body {
        ///            margin: 0
        ///        }
        ///        
        ///        article,
        ///        aside,
        ///        details,
        ///        figcaption,
        ///        figure,
        ///        footer,
        ///        header,
        ///        hgroup,
        ///        main,
        ///        menu,
        ///        nav,
        ///        section,
        ///        summar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SeniorReport {
            get {
                return ResourceManager.GetString("SeniorReport", resourceCulture);
            }
        }
    }
}
